# Generated by Django 5.0.6 on 2024-07-10 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0008_alter_book_options_alter_book_tag"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="author",
            options={"verbose_name_plural": "Books and Authors"},
        ),
    ]
