# Generated by Django 5.0.6 on 2024-07-12 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0010_alter_book_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="catgegory",
            new_name="category",
        ),
    ]
